name: "Build Firmware (Manual) on bcm2712"

permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  build-ekh-bcm2712:
    name: Build ekh-bcm2712
    uses: ./.github/workflows/build-firmware.yml
    with:
      board: ekh-bcm2712
      target: bcm27xx
      subtarget: bcm2712
      description: "Raspberry Pi 5, CM5"